# Generated by Django 5.2.7 on 2025-10-12 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_pg_alter_users_email_alter_users_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.pgs')),
            ],
        ),
    ]
