# Generated by Django 5.2.7 on 2025-11-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
